set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR 6502)

set(CMAKE_C_COMPILER cl65)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_FLAGS_INIT "-D__fastcall__=")
set(CMAKE_C_FLAGS_DEBUG_INIT "-D__fastcall__= -g")
set(CMAKE_C_FLAGS_RELEASE_INIT "-D__fastcall__= -O")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-D__fastcall__= -O -g")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-D__fastcall__= -Os")
